In [ ]:
#pip install tradeapi

In [1]:
from tradeapi import FinamApi

In [5]:
token  = 'eyJraWQiOiI3NDcwZDdlMy1kOGEwLTQyZWQtYTkzZi1hZDIxODFlYWRmMjEiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJwYXJlbnQiOiI3ZTJmNjViOS1kZDAzLTQ4Y2ItODhlYy1kYjg0ZTc0ZjYwMWQiLCJhcGlUb2tlblByb3BlcnRpZXMiOiJINHNJQUFBQUFBQUFfeTJTUFpMYk1BeUZkMHc1OXJoRXVlV204MHdLei00RktJcVVGSnVTekI5YlRxTm02NlRJZ1hLYVRObzA2VkxuSEhrZzFId1BKQUFCQkxUXzllUG5uMy12dE5tcjU3OXF2M2w1T3U0TzI0LWhEazB4N25jekhUOGNLdTNuc1dnd00ydXRVeXg2ODQ3VnpwTm43ZTNjRm5VMmktWVM1X3RZOHNZeG1hSlQwRVdUdWJKT19XQldMWEVoU1h6SW9yUDJVVFRhVmVXLUhyMW95S0paX0taMnF5WlJhMFM5LUcwS1JaMzBNYmRhNHJxelc3VzhZNzQwZy1pYWQxbnJYVWE1OTdvcE9tanBiekRpSDlyMXZQWTlQTmI3aDV3bkxmVmpKM1hpWGQ2VHpwRUh2OVNES1EwdkJnUG1DNXREWFF6djZ5X0ZHS1pRZHJKRTB4LTNCN1hFcWR6SGFRMkkwX3VwR0NuWS1QeGI3UlVwYldjZ1dzYVZnU09XQ1Z3WjdNQUlxYXFfZlgybkxmTTdLUXlUZ1FEVDlZQzNER1NhbTZWZDg3a2ZHdjZzelRQdG5QT0xEeWVxWEQ5b09qRDkwdVQwb0swYnNWWlNEa1UyRHZHdERhUTZoNDloMnFSNm00R01pSXQ1QUZ6bHdnMWh4b0JCaGtlWnludU5Kbnk0a2NMVUFjLUlQY016OEM2TW0xRXNlTWVvU1dIa1ZINHc4QnhQaGEtRmIzQnlvV0R3eEpCcTJvWnNhalFYOVFqWXlJQXJ0c2dGUHNIc09xQkhsWmpRR05aSEtqVjRSYnJjcUVyb0VlYUlUNlFIUHBFMTNIY3VNU09sNHUyUzdKZ1B5UlZHMEJoMlktY2tHOGVoYlRUSjFrbDJTN0xRbDZmX3pEeU1ZYjBEQUFBIiwiemlwcGVkIjp0cnVlLCJjcmVhdGVkIjoiMTc0ODM3MDQwNSIsInJlbmV3RXhwIjoiMTc3OTkwNjQ2NSIsInNlc3MiOiJINHNJQUFBQUFBQUEvMU9LNFZJeFRUUk9NVTQxU2RSTk1rNDExVFV4TjBuVlRUSXpOdEJOdERSTE5Vc3hTMHN5U3pFU0Vyb3c0Y0x1QzFzdjdMclllR0hEaGIwWHRseHNrT0s2TUFNb3R2dGkzNFZkU2lLSk9ha1ZPZmxscVpZR0RwV0plU21wRlhwRnBRRCt4S0tpWGdBQUFBIiwiaXNzIjoidHhzZXJ2ZXIiLCJrZXlJZCI6Ijc0NzBkN2UzLWQ4YTAtNDJlZC1hOTNmLWFkMjE4MWVhZGYyMSIsInR5cGUiOiJUcmFkZUFwaTIwIiwic2VjcmV0cyI6IkVDVXV6b0NiUFR4ZWNuOWd4ejA1cWc9PSIsInRzdGVwIjoiZmFsc2UiLCJleHAiOjE3Nzk5MDY0MDUsImp0aSI6IjcwMGE0NjY5LWE5ZTktNGY5YS1iOGMyLTBmMjMyNjY5YTg5MSJ9.h-IrFi-MEAn8CeZ3QDWdg9zgoMsdqVNvpRl5a0ZUzgPLaB1lht1sZqCKl2yDPzyuzW0fRSffoG0P4ZKiKwCb-Q'
fnm = FinamApi(token = token)

#Активы, которые есть в Финаме 
fnm.assets.head()

              symbol       id  ...      type                           name
0           WSO@RUSX   571681  ...  EQUITIES                   Watsco, Inc.
1  RU000A102KN2@MISX  2235969  ...     BONDS                     КалинОбл20
2  RU000A109NA8@MISX  5353655  ...     BONDS                      СолСАТЛ01
3          VYGR@XNGS   450290  ...  EQUITIES     Voyager Therapeutics, Inc.
4          2822@RUSX  4445216  ...     FUNDS  CSOP FTSE China A50 ETF (HKD)

[5 rows x 7 columns]

In [7]:
ls = fnm.orderbook(symbol = 'SBER@MISX')

In [20]:
ls = fnm.orderbook(symbol = 'SBER@MISX')
ls['offer']

     price  volume   side
0   310.17   512.0  OFFER
1   310.18    97.0  OFFER
2   310.19    16.0  OFFER
3   310.20   437.0  OFFER
4   310.21  1046.0  OFFER
5   310.23    96.0  OFFER
6   310.24    55.0  OFFER
7   310.30     1.0  OFFER
8   310.32    33.0  OFFER
9   310.33   610.0  OFFER
10  310.37   500.0  OFFER
11  310.40   601.0  OFFER
12  310.43     3.0  OFFER
13  310.47  1849.0  OFFER
14  310.50    70.0  OFFER
15  310.58    60.0  OFFER
16  310.59   200.0  OFFER
17  310.61   501.0  OFFER
18  310.62  1201.0  OFFER
19  310.65     4.0  OFFER

In [ ]:
def get_price(symbol,volume, direction = 'BUY'):
    orderbook = fnm.orderbook(symbol)
    dir = 'offer' if direction == 'BUY' else 'bid'
    df = orderbook[dir]
    vol_cumsum = df['volume'].cumsum()
    series = vol_cumsum < volume
    idx = series[series == False].index[0]
    price = df.loc[idx,'price']
    return price

In [24]:
get_price('SBER@MISX',volume = 4000)

310.4